### ISSUE TITLE
Firebase DB

### ISSUE THREAD

**Issue by freqq68** [balsimpson/alexa-radio-skill#3]
Hello @balsimpson 

I get this 
![image](https://github.com/balsimpson/alexa-radio-skill/assets/4027268/5fd43e40-0839-4fa0-b5b1-0a50398a4688)

I dunno if it's me i'm wrong or is it completly broken ...

here how Iv'e read the credetials 

![image](https://github.com/balsimpson/alexa-radio-skill/assets/4027268/64236971-9c57-4479-878a-5db42ba3feea)

thks

**Comment by balsimpson** [comment]
Hey sorry. I've not updated this in a long time.

**Comment by HammyHavoc** [comment]
@freqq68, I'm getting these errors in my Vercel logs:

```
firebase-error [FirebaseError: Missing or insufficient permissions.] {
code: 'permission-denied',
customData: undefined,
toString: [Function (anonymous)]
}
getDocFromFirestore-error [FirebaseError: Missing or insufficient permissions.] {
code: 'permission-denied',
customData: undefined,
toString: [Function (anonymous)]
}
```

In all likelihood, you're seeing the same problem. It appears that the contemporary default Firebase permissions do not allow access. Not being overly familiar with Firebase these days, I'm currently digging into what the correct Rules for Firebase would look like versus the default:

```
rules_version = '2';

service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if false;
    }
  }
}
```

Whilst people on the web and various LLMs will tell you to `allow read, write` or similar, this allows anybody to read and write the database, which is obviously bad from a security perspective, but also one of potentially getting an astronomically high bill for someone's abuse of your database.

**Comment by HammyHavoc** [comment]
@freqq68, looking at your screenshot, I can see the problem you're facing:

- `projectId` should be `FIREBASE_PROJECT_ID`
- `apiKey` should be `FIREBASE_API_KEY`

**Comment by freqq68** [comment]
I'm out of the project now :/ Maybe I retry later. Thank's 🥇
